apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mariadb-galera
  namespace: spring-petclinic
spec:
  helmVersion: v3
  targetNamespace: spring-petclinic
  releaseName: mariadb-galera
  wait: true
  test:
    enable: true
  chart:
    repository: https://charts.trials.tac.bitnami.com/demo
    name: mariadb-galera
    version: 4.4.0
  values:
    clusterDomain: k8s-diy.lab.home
    replication:
      enabled: false
    rootUser:
      password: petclinic
    db:
      user: petclinic
      password: petclinic
      name: petclinic
    persistence:
      size: 50Gi
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: helm.sh/chart
              operator: In
              values:
              - mariadb-galera-4.4.0
          topologyKey: kubernetes.io/hostname