apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mysql
  namespace: spring-petclinic
spec:
  helmVersion: v3
  targetNamespace: spring-petclinic
  releaseName: mysql
  wait: true
  test:
    enable: true
  chart:
    repository: https://charts.trials.tac.bitnami.com/demo
    name: mysql
    version: "6.14.5"
  values:
    replication:
      enabled: false
    root:
      password: petclinic
    db:
      user: petclinic
      password: petclinic
      name: petclinic